### ISSUE TITLE
Potentially decide on a formatting guide?

### ISSUE THREAD

**Issue by bredcat999** [TheTimeBunny/TimeBom#3]
Could we decide on a formatting guide for the code? I've noticed the formatting and styling is sporadic and sometimes inconsistent.

**Comment by ajskateboarder** [comment]
[This SO answer](https://stackoverflow.com/a/841083/16019146) suggests some formatting guides/programs

**Comment by bredcat999** [comment]
Thanks, I was already planning on adding some .clang-format files to the repos

**Comment by ajskateboarder** [comment]
Your style guide is so based

**Comment by bredcat999** [comment]
> Your style guide is so based

i know right
I will definitely not be permanently scarred by putting classes in their own separate files
