### ISSUE TITLE
Specify more information in the README

### ISSUE THREAD

**Issue by windowsmas** [TheTimeBunny/TimeBom#5]
Edit: Thanks breadcat, i'm excited for the next update.
Thanks

**Comment by bredcat999** [comment]
Sorry about that, the README will be worked on soon. I’m waiting for @Steve4Space  to commit changes so I can make some big changes to the repository’s structure.

**Comment by Sfreyjr** [comment]
Works letting out late, as I'm waiting for some5hing. However, be rest assured that changes will be made really soon, and then the Readme will be updated. I just have some unpushed changes that need pushing before any changes can be made.

**Comment by windowsmas** [comment]
Thanks. :D
great game engine!

**Comment by Sfreyjr** [comment]
Thank you!

**Comment by windowsmas** [comment]
Thanks for your contribution for this issue.

I've came up with an example README :)
Here ya go! 

### TimeBom
[insert timebom logo here]
**TimeBom** is a more friendly and open-source game engine developed by a team of contributors:

**Creator (Programmer, Artist, Sound FX, Designer, Publisher)**
GlitchJustExists

**Contributors**
bredcat999
redstone-scratch

We are excited to expand our project and are ambitious to be one of the best game engines!
Thanks,
The TimeBom Team
