### ISSUE TITLE
Create style guidelines

### ISSUE THREAD

**Issue by redstone-dev** [TheTimeBunny/TimeBom#9]

**Comment by redstone-dev** [comment]
I have created a draft. To move this from In Progress to Done, we need to finalize them.

Anyone got any ideas?

**Comment by ajskateboarder** [comment]
You could configure `clang-format` with your [DraftStyleGuide.md](https://github.com/TheTimeBunny/TimeBom/blob/master/DraftStyleGuide.md). 

There's some docs for configuring Clang's formatting style [here](https://clang.llvm.org/docs/ClangFormatStyleOptions.html)
